# (14) tmask mismatch

**Motivation**: <br>

In [1]:
# HIDE CODE


import os, sys
from IPython.display import display

# tmp & extras dir
git_dir = os.path.join(os.environ['HOME'], 'Dropbox/git')
extras_dir = os.path.join(git_dir, 'jb-Ca-fMRI/_extras')
fig_base_dir = os.path.join(git_dir, 'jb-Ca-fMRI/figs')
tmp_dir = os.path.join(git_dir, 'jb-Ca-fMRI/tmp')

# GitHub
sys.path.insert(0, os.path.join(git_dir, '_Ca-fMRI'))
from figures.fighelper import *
from analysis.final import *
from utils.render import *

# warnings, tqdm, & style
warnings.filterwarnings('ignore', category=DeprecationWarning)
from tqdm.notebook import tqdm
%matplotlib inline
set_style()

In [2]:
def _tmask_delta_df(path, full=False):
    df = []
    for key, func in tqdm(mice.bold.items(), disable=not full):
        try:
            f = next(
                f for f in os.listdir(path) if
                all(e in f for e in key.split('_'))
            )
            tmask = pd.read_csv(pjoin(path, f)).values
            tmask = tmask.sum()
        except StopIteration:
            tmask = np.nan
            
        if full:
            run_raw_t = float(
                mice.bold_preproc[key].load_ants().shape[-1])
        else:
            run_raw_t = np.nan

        df.append({
            'key': [key],
            'task': [func.task],
            'run_t': [float(func[:].shape[1])],
            'run_raw_t': [run_raw_t],
            'tmask_t': [tmask],
        })
    df = pd.DataFrame(merge_dicts(df))
    return df

In [3]:
desc = {
    'ca2': 'preproc',
    'bold': 'rabies-hp',
}
mice = Mice(128)
mice.setup_preproc_data(desc=desc)
mice.setup_func_data(task=None, exclude=False, desc=desc)

base_dir = '/mnt/storage/hadi/Ca-fMRI/gabe_data'

## Processed data

### 1) reoriented_data_highpass

In [4]:
path = 'reoriented_data_highpass/frame_censoring_mask'
df = _tmask_delta_df(pjoin(base_dir, path), False)
delta = (df['run_t'] - df['tmask_t']).values

In [5]:
delta

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
collections.Counter(delta).most_common()

[(0.0, 200)]

In [7]:
percent_correct1 = 100 * collections.Counter(delta).get(0., 0.) / len(delta)
print(f"{percent_correct1:0.2f} % correct")

100.00 % correct

In [8]:
mice.bold['sub-SLC02_ses-2_run-3'].shape

(2766, 519)

### 2) reoriented_data

In [9]:
path = 'reoriented_data/frame_censoring_mask'
df = _tmask_delta_df(pjoin(base_dir, path), False)
delta = (df['run_t'] - df['tmask_t']).values

In [10]:
delta

array([-26., -25., -29., -24., -20., -21., -23., -25., -20., -26., -27.,
       -20., -26., -27., -21., -25., -24., -19., -28., -28., -23., -26.,
       -25., -26., -27., -27., -22., -16., -20., -22., -25., -29., -25.,
       -29., -28., -27., -24., -26., -26., -26., -22., -28., -19., -29.,
       -24., -26., -26., -25., -29., -19., -24., -22., -12., -29., -21.,
       -26., -25., -24., -25., -27., -25., -18., -26., -13., -19., -23.,
       -28., -23., -24., -29.,  -8., -10., -20., -26., -24., -27., -26.,
       -27., -25., -26., -25., -29., -22., -27., -22., -23., -27., -20.,
       -27., -20., -17., -21., -25., -28., -26., -29., -29., -23., -25.,
       -24., -21., -26., -22., -25., -24., -28., -29., -29., -22., -24.,
       -25., -24., -25., -29., -27., -26., -26., -27., -29., -26., -25.,
       -27., -25., -15., -22., -23., -24., -28., -25., -29., -27., -28.,
       -26., -23., -27., -26., -25., -22., -29., -28., -27., -29., -24.,
       -23., -28., -27., -12., -27., -25., -26., -11., -13., -24., -25.,
       -20., -23., -17., -23., -27., -17., -27., -19., -24., -25., -26.,
       -28., -25., -18., -26., -29., -23., -29., -18., -28., -28., -29.,
       -27., -29., -29., -22., -28., -27., -27., -21., -26., -28., -22.,
       -29., -25., -26., -24., -29., -25., -29., -25., -26., -23., -15.,
       -22., -26.])

In [11]:
collections.Counter(delta).most_common()

[
    (-26.0, 29),
    (-25.0, 28),
    (-29.0, 25),
    (-27.0, 24),
    (-24.0, 17),
    (-28.0, 16),
    (-23.0, 13),
    (-22.0, 13),
    (-20.0, 8),
    (-21.0, 6),
    (-19.0, 5),
    (-18.0, 3),
    (-17.0, 3),
    (-12.0, 2),
    (-13.0, 2),
    (-15.0, 2),
    (-16.0, 1),
    (-8.0, 1),
    (-10.0, 1),
    (-11.0, 1)
]

In [12]:
percent_correct2 = 100 * collections.Counter(delta).get(0., 0.) / len(delta)
print(f"{percent_correct2:0.2f} % correct")

0.00 % correct

### Sum of % corrects

In [13]:
percent_correct1 + percent_correct2

100.0

## Now check with ```desc=rabies``` loaded

In [14]:
desc = {
    'ca2': 'preproc',
    'bold': 'rabies',
}
mice = Mice(128)
mice.setup_preproc_data(desc=desc)
mice.setup_func_data(task=None, exclude=False, desc=desc)

base_dir = '/mnt/storage/hadi/Ca-fMRI/gabe_data'

## Processed data

### 1) reoriented_data_highpass

In [15]:
path = 'reoriented_data_highpass/frame_censoring_mask'
df = _tmask_delta_df(pjoin(base_dir, path), False)
delta = (df['run_t'] - df['tmask_t']).values

In [16]:
delta

array([26., 25., 29., 24., 20., 21., 23., 25., 20., 26., 27., 20., 26.,
       27., 21., 25., 24., 19., 28., 28., 23., 26., 25., 26., 27., 27.,
       22., 16., 20., 22., 25., 29., 25., 29., 28., 27., 24., 26., 26.,
       26., 22., 28., 19., 29., 24., 26., 26., 25., 29., 19., 24., 22.,
       12., 29., 21., 26., 25., 24., 25., 27., 25., 18., 26., 13., 19.,
       23., 28., 23., 24., 29.,  8., 10., 20., 26., 24., 27., 26., 27.,
       25., 26., 25., 29., 22., 27., 22., 23., 27., 20., 27., 20., 17.,
       21., 25., 28., 26., 29., 29., 23., 25., 24., 21., 26., 22., 25.,
       24., 28., 29., 29., 22., 24., 25., 24., 25., 29., 27., 26., 26.,
       27., 29., 26., 25., 27., 25., 15., 22., 23., 24., 28., 25., 29.,
       27., 28., 26., 23., 27., 26., 25., 22., 29., 28., 27., 29., 24.,
       23., 28., 27., 12., 27., 25., 26., 11., 13., 24., 25., 20., 23.,
       17., 23., 27., 17., 27., 19., 24., 25., 26., 28., 25., 18., 26.,
       29., 23., 29., 18., 28., 28., 29., 27., 29., 29., 22., 28., 27.,
       27., 21., nan, 26., 28., 22., 29., 25., 26., 24., 29., 25., 29.,
       25., 26., 23., 15., 22., 26.])

In [17]:
collections.Counter(delta).most_common()

[
    (26.0, 29),
    (25.0, 28),
    (29.0, 25),
    (27.0, 24),
    (24.0, 17),
    (28.0, 16),
    (23.0, 13),
    (22.0, 13),
    (20.0, 8),
    (21.0, 6),
    (19.0, 5),
    (18.0, 3),
    (17.0, 3),
    (12.0, 2),
    (13.0, 2),
    (15.0, 2),
    (16.0, 1),
    (8.0, 1),
    (10.0, 1),
    (11.0, 1),
    (nan, 1)
]

In [18]:
percent_correct1 = 100 * collections.Counter(delta).get(0., 0.) / len(delta)
print(f"{percent_correct1:0.2f} % correct")

0.00 % correct

In [19]:
mice.bold['sub-SLC02_ses-2_run-3'].shape

(2766, 541)

### 2) reoriented_data

In [20]:
path = 'reoriented_data/frame_censoring_mask'
df = _tmask_delta_df(pjoin(base_dir, path), False)
delta = (df['run_t'] - df['tmask_t']).values

In [21]:
delta

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
collections.Counter(delta).most_common()

[(0.0, 201)]

In [23]:
percent_correct2 = 100 * collections.Counter(delta).get(0., 0.) / len(delta)
print(f"{percent_correct2:0.2f} % correct")

100.00 % correct

### Sum of % corrects

In [24]:
percent_correct1 + percent_correct2

100.0